name: CI — Payment Service

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry==1.7.1

      - name: Install dependencies
        run: poetry install

      - name: Lint with Ruff
        run: poetry run ruff check app/ tests/

      - name: Run tests
        run: poetry run pytest -v --tb=short

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t eventflow-payment-service:ci .
